name: Lint Android

on:
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/lint-android.yml"
      - "packages/react-native-legal/android/**"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint-swift:
    name: Lint Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set Java version
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Lint Android with Spotless and ktfmt
        run: ./scripts/lint-android.sh

