name: Lint ObjC

on:
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/lint-objc.yml"
      - "packages/react-native-legal/ios/**"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint-swift:
    name: Lint ObjC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Lint ObjC with clang-format
        uses: RafikFarhad/clang-format-github-action@v4
        with:
          sources: "packages/react-native-legal/**/*.h,packages/react-native-legal/**/*.m,packages/react-native-legal/**/*.mm"
          style: file

